import Hero from './Hero/Hero';
import Navbar from './Navbar/Navbar';
import Footer from './Footer/Footer';
import Service from './Service/Service';
import Location from './Location/Location';
import PopularService from './PopularService/PopularService';
import AppDownload from './AppDownload/AppDownload';
import FrequentlyAskedQuestion from './FrequentlyAskedQuestion/FrequentlyAskedQuestion';
import Testimonial from './Testimonial/Testimonial';
import ExclusiveStore from './ExclusiveStore/ExclusiveStore';
import Subscribe from './Subscribe/Subscribe';
import Guarantee from './Guarantee/Guarantee';
import HowItWorks from './HowItWorks/HowItWorks';
export { Hero, Navbar, Footer, Service, Location, PopularService, AppDownload, FrequentlyAskedQuestion, Testimonial, ExclusiveStore, Subscribe, Guarantee, HowItWorks };