import Hero from './Hero/Hero';
import Navbar from './Navbar/Navbar';
import Footer from './Footer/Footer';
import Service from './Service/Service';
import Location from './Location/Location';
import PopularService from './PopularService/PopularService';
import AppDownload from './AppDownload/AppDownload';
import FrequentlyAskedQuestion from './FrequentlyAskedQuestion/FrequentlyAskedQuestion';
import Testimonial from './Testimonial/Testimonial';
export { Hero, Navbar, Footer, Service, Location, PopularService, AppDownload, FrequentlyAskedQuestion, Testimonial };